# Generated by Django 4.0.2 on 2022-03-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dncapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookyyyy', models.CharField(max_length=20)),
                ('cookmm', models.CharField(max_length=20)),
                ('cookdd', models.CharField(max_length=20)),
                ('cookname', models.CharField(max_length=20)),
            ],
        ),
    ]
