# Generated by Django 4.0.2 on 2022-03-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dncapp', '0003_post_delete_cook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cookname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mm',
        ),
    ]
