# Generated by Django 4.0.2 on 2022-03-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dncapp', '0005_post_cookname_post_dd_post_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='yyyy',
            field=models.TextField(default=''),
        ),
    ]
